### ISSUE TITLE
Only the first metric in a file gets registered

### ISSUE THREAD

**Issue by chibuikesebastine** [danielrataj/sails-hook-prometheus#11]
This is my Counter metrics. As you can see i have multiple in one file.

`
    /* global sails */

    const LoginAttemptCounter = sails.hooks.prometheus.counter.setup({
      name: 'app_login_attempt',
      help: 'Track the status of login attempts (success or failed).',
      labelNames: ['status', 'code'],
    })
    
    const InitiateOnboardingCounter = sails.hooks.prometheus.counter.setup({
      name: 'initiate_onboarding',
      help: 'Track the status of onboarding initiation.',
      labelNames: ['status', 'code', 'step'],
    })
    
    const ImageUploadCounter = sails.hooks.prometheus.counter.setup({
      name: 'image_upload',
      help: 'Track the status of image upload.',
      labelNames: ['status', 'code'],
    })
    
    const ImageDownloadCounter = sails.hooks.prometheus.counter.setup({
      name: 'image_download',
      help: 'Track the status of image download.',
      labelNames: ['status', 'code'],
    })
    
    const FaceVerificationCounter = sails.hooks.prometheus.counter.setup({
      name: 'face_verification',
      help: 'Track the status of facial verification.',
      labelNames: ['status', 'code'],
    })
    
    const CompleteOnboardingCounter = sails.hooks.prometheus.counter.setup({
      name: 'complete_onboarding',
      help: 'Track the status of the complete onboarding step.',
      labelNames: ['status', 'code'],
    })
    
    
    module.exports = {
      /**
       * Track login attempts metrics.
       */
      loginAttempts: {
        success: (code = 200) =>
          LoginAttemptCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400) =>
          LoginAttemptCounter.inc({ amount: 1, labels: { status: 'failed', code } }),
      },
    
      /**
       * Track initiate-onboarding metrics.
       */
      initiateOnboarding: {
        success: (code = 200) =>
          InitiateOnboardingCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400, step) =>
          InitiateOnboardingCounter.inc({ amount: 1, labels: { status: 'failed', code, step } }),
      },
    
      /**
       * Track image upload metrics.
       */
      imageUpload: {
        success: (code = 200) =>
          ImageUploadCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400) =>
          ImageUploadCounter.inc({ amount: 1, labels: { status: 'failed', code } }),
      },
    
      /**
       * Track image download metrics.
       */
      imageDownload: {
        success: (code = 200) =>
          ImageDownloadCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400) =>
          ImageDownloadCounter.inc({ amount: 1, labels: { status: 'failed', code } }),
      },
    
      /**
       * Track image face verification.
       */
      faceVerification: {
        success: (code = 200) =>
          FaceVerificationCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400) =>
          FaceVerificationCounter.inc({ amount: 1, labels: { status: 'failed', code } }),
      },
    
      /**
       * Track image download metrics.
       */
      completeOnboarding: {
        success: (code = 200) =>
          CompleteOnboardingCounter.inc({ amount: 1, labels: { status: 'success', code } }),
        failed: (code = 400) =>
          CompleteOnboardingCounter.inc({ amount: 1, labels: { status: 'failed', code } }),
      },
    };
`

However, when i run the application only the first counter  in this file seems to get registered.

**Comment by danielrataj** [comment]
Hi, you're right. I can't even believe I missed it! 🤔
I'll check the issue during the upcoming week.

Thank you for reporting it.

**Comment by chibuikesebastine** [comment]
I have implemented a fix for this. But i am on version 0.4.0, can we push a 0.4.1 release that fixes this issue for 0.4.Xs?

**Comment by danielrataj** [comment]
Thank you very much. I released a new version on NPM - 0.6.0
It is really nice of you. Have a great Sunday.
