### ISSUE TITLE
Use a prefix for the /metrics endpoint

### ISSUE THREAD

**Issue by gianco** [danielrataj/sails-hook-prometheus#7]
Would be possible to introduce a config parameter to personalize the `/metrics` endpoint (i.e. `/api/v1/metrics`)?

We would like to use this, but are stuck on this. 

TYIA

**Comment by danielrataj** [comment]
Hi, thank you for the idea. I released a new version (0.5.0) with the option to customize the final URL.
Just install the latest update and adjust your router to the URL you prefer. The code example is in the README file:
https://github.com/danielrataj/sails-hook-prometheus#custom-metrics-endpoint

**Comment by gianco** [comment]
Cool! Thank you very much.
